version: '3.9'
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0.1
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev

  shared:
    container_name: shared
    build:
      context: ./frontends/sclinico-shared
      dockerfile: ./Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./frontends/sclinico-shared:/usr/src/app

  accounts-app:
    container_name: accounts-app
    build:
      context: ./frontends/sclinico-accounts
      dockerfile: ./Dockerfile
    ports:
      - 4201:4201
    volumes:
      - ./frontends/sclinico-accounts:/src/sclinico-accounts
      - /src/sclinico-accounts/node_modules

  appointments:
    container_name: appointments
    build:
      context: ./frontends/sclinico-appointments
      dockerfile: ./Dockerfile
    ports:
      - 4202:4202
    volumes:
      - ./frontends/sclinico-appointments:/src/sclinico-appointments
      - /src/sclinico-appointments/node_modules

  navbar:
    container_name: navbar
    build:
      context: ./frontends/navbar
      dockerfile: ./Dockerfile
    ports:
      - 4203:4203
    volumes:
      - ./frontends/navbar:/src/navbar
      - /src/navbar/node_modules

  root:
    container_name: root
    build:
      context: ./frontends/sclinico-root
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./frontends/sclinico-root:/usr/src/app